[project]
name = "mlops-lecture"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dvc>=3.66.1",
    "ipykernel>=7.2.0",
    "kedro>=1.2.0",
    "mlflow>=3.9.0",
    "pandas>=2.3.3",
    "scikit-learn>=1.8.0",
]
